# Generated by Django 3.2.4 on 2021-06-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [

    ]
